### ISSUE TITLE
能否输入一些文字，文字大小和颜色可调整

### ISSUE THREAD

**Issue by kjtown** [kejiacheng/kscreenshot#10]
如果能输入一些文字，文字大小和颜色可调整，这个功能就比较好了。另外希望能出一个前端使用的DEMO，Vue.js的demo能出一个吗？不知道怎么调用。

**Comment by kejiacheng** [comment]
可以输入文字以及修改颜色，暂时文字大小不可以调整。demo在README里面写了的。
