### ISSUE TITLE
默认笔刷怎么设置细一些，调用方法是什么。

### ISSUE THREAD

**Issue by kjtown** [kejiacheng/kscreenshot#11]

**Comment by kejiacheng** [comment]
目前没实现默认笔刷，但是可在选择笔刷的时候，调节笔刷的粗细

**Comment by kjtown** [comment]
谢谢，最好能抽空优化一下笔刷粗细，因为很多用户，实际是不是太了解这些操作，能默认较细的一种笔刷，对他们来说，是更简便的。

**Comment by kejiacheng** [comment]
嗯嗯  了解

**Comment by kejiacheng** [comment]
该功能已经增加  在toolShow下的drawLIne可输入数值，范围为1-10

**Comment by kjtown** [comment]
要怎么调用这个设置，能把调用代码写出来一下吗，谢谢

**Comment by kejiacheng** [comment]
toolShow: {drawLine: 5}
