### ISSUE TITLE
编译后的kss.js文件ie无法进行截图怎么解决？

### ISSUE THREAD

**Issue by henuyuxiang** [kejiacheng/kscreenshot#12]
ie下kss.js报错，但相同代码其他浏览器可以正常截取，唯独ie不可以，该控件是不是自身不支持ie浏览器截图？
ie下js错误代码：
SCRIPT1006: 缺少 ')' 
kss.js, 行1 字符192581
SCRIPT5009: “kscreenshot”未定义 
getOfficeDoc.ht?id=10000125194239, 行51 字符2

**Comment by kejiacheng** [comment]
嗯嗯  不好意思  的确不兼容ie的

**Comment by henuyuxiang** [comment]
> 嗯嗯 不好意思 的确不兼容ie的

嗯嗯  好的 谢谢
