### ISSUE TITLE
我在electron直接调用你的插件，结果一调用开始截图方法就会报错

### ISSUE THREAD

**Issue by luoluoluojiayu** [kejiacheng/kscreenshot#13]
import kscreenshot from 'kscreenshot';

//65指键盘中的A
const myScreen=new kscreenshot(
    {
        key: 65
    }
)
myScreen.startScreenShot();

类似这样调用，可是会提示

kss.js:1 Uncaught (in promise) TypeError: Illegal invocation
    at new A (kss.js:1)
    at A (kss.js:1)
    at e.NodeParser (kss.js:1)
    at kss.js:1
    at <anonymous>

请问怎么解决

**Comment by kejiacheng** [comment]
这个应该跟我这个包没有关系  你引用是不是有问题
