### ISSUE TITLE
截图区域放大

### ISSUE THREAD

**Issue by GracefulTing** [kejiacheng/kscreenshot#15]
截图完毕会发现区域内的内容放大了，而且页面中的图片也都空白了，会报错跨域，这个应该怎么解决呀？

**Comment by kejiacheng** [comment]
用的是chrome吗，我这截图工具没有做兼容处理的。跨域报错这个问题，其实是因为我用的第三方工具（html2canvas）导致的。有一个办法可以解决，就是把跨域图片变为本地图片，不过感觉成本太大，就没有实现。

**Comment by GracefulTing** [comment]
那选择截图区域后，会放大的这个问题呢？怎么解决呀？
如果这种格式可以试试这个，我之前做导出图片有跨域问题这么解决的：html2canvas(document.querySelector('.activeImg'),{
            // allowTaint:true,   //允许污染图片
            useCORS: true,
            height: $(".activeImg").outerHeight()
          }).then(function(canvas) {

**Comment by GracefulTing** [comment]
项目要的急，看到您这个插件的时候简直救我一命啊！希望能帮助我解决一下，十分感谢！

**Comment by kejiacheng** [comment]
useCORS: true . 这个我已经加上了，不过没有效果。
放大的问题，你那边用的chrome吗？

**Comment by GracefulTing** [comment]
是的，我看您的demo截图里没有这样的问题

**Comment by kejiacheng** [comment]
等一下

**Comment by GracefulTing** [comment]
好的好的，麻烦了，我在看看

**Comment by kejiacheng** [comment]
应该跟画布的宽高有关

**Comment by GracefulTing** [comment]
嗯，那这个需要我设置吗？还是什么呀？不造自己该怎么弄

**Comment by kejiacheng** [comment]
不是  应该你兼容问题 你用的win10吧

**Comment by kejiacheng** [comment]
我这边看看  怎么办

**Comment by GracefulTing** [comment]
嗯嗯，好的，我也看一下

**Comment by kejiacheng** [comment]
你看下 把外层的canvas的style属性取消掉

**Comment by kejiacheng** [comment]
我这边试了几台电脑都没问题，复现不了 不好调试

**Comment by GracefulTing** [comment]
好的 我试一下

**Comment by kejiacheng** [comment]
可以了吗？

**Comment by GracefulTing** [comment]
没有哎，我修改的createDragDom.js里mousemoveEvent的let style

**Comment by GracefulTing** [comment]
对了，还有就是我完成后怎么能直接发出去呢  昨天偶然可以粘贴一个，但是很多情况下我都粘贴不了

**Comment by kejiacheng** [comment]
我先问下  你这是打包成客户端的吗

**Comment by GracefulTing** [comment]
不是，就按照npm install到项目里  在做一个网页版的聊天室，需要截图功能

**Comment by kejiacheng** [comment]
复制功能，就跟我readme写的一样，使用js，目前没有找到可以兼容所有客户端的方法

**Comment by GracefulTing** [comment]
嗯嗯，好的  我先研究下您的代码吧，实在是太厉害了，看不懂

**Comment by kejiacheng** [comment]
。。。实在抱歉了，因为这截图功能，如果用在客户端到还好，如果用在网页端，实在有太大的局限性了。

**Comment by GracefulTing** [comment]
好吧，最后的救命稻草呀，昨天刚给，明天我就需要做出来，有点崩溃了

**Comment by kejiacheng** [comment]
。。。。这需求太强人所难了吧

**Comment by GracefulTing** [comment]
他们认为找个插件能用就好了吧大概，给的急，然后我一个人，昨天找了一下午都没找到，最后看到您的博客才有了希望，真的是，我让朋友试一下看看他们使用这个有问题吗

**Comment by kejiacheng** [comment]
他们想的太容易了

**Comment by GracefulTing** [comment]
嗯呢，现在真的是崩溃

**Comment by GracefulTing** [comment]
新起了一个项目，看控制台是放大了1.5倍

**Comment by kejiacheng** [comment]
你试过在其他电脑上吗？因为我这边试了很多台都是没问题的。
我这边无法复现，实在没法调。

**Comment by GracefulTing** [comment]
嗯嗯 我找到问题了，是分辨率的问题，我把电脑系统显示分辨率设为100%后正常。所以这个是不是需要计算显示的分辨率，需要计算。

**Comment by GracefulTing** [comment]
window.devicePixelRatio 通过这个看一下，但是我不知道你这个怎么写的？方便加qq或者微信吗？

**Comment by kejiacheng** [comment]
嗯嗯 明白了  375615453

**Comment by kejiacheng** [comment]
我分辨率的没有考虑  这的确是个问题

**Comment by GracefulTing** [comment]
嗯嗯，您看这个好解决吗
