### ISSUE TITLE
new 时候为什么一直报错

### ISSUE THREAD

**Issue by xiangzimimi** [kejiacheng/kscreenshot#18]

**Comment by kejiacheng** [comment]
是怎么报错的

**Comment by TheRenTOP** [comment]
大佬能不能把你的dome放出来看一下，我这边也是一直在报错，不知道原因啊

**Comment by kejiacheng** [comment]
> 大佬能不能把你的dome放出来看一下，我这边也是一直在报错，不知道原因啊

demo在readme里面有呀，你把报错的信息，发出来看一下

**Comment by TheRenTOP** [comment]
import kscreenshot from '/kscreenshot'
引入的时候报意外
Unexpected identifier

**Comment by TheRenTOP** [comment]
可能是我不会用es6的语法，所以我不知道什么原因啊

**Comment by kejiacheng** [comment]
是es6的原因，import需要babel转译后才能用

**Comment by TheRenTOP** [comment]
好的，谢谢

**Comment by kejiacheng** [comment]
你如果不会用babel的话，你直接用script引用下载来的js文件。
当然现在es6是必备的，所以你最好能学一下

**Comment by TheRenTOP** [comment]
也正在学习es6了，这个功能搞得我头晕啊，触及我的知识盲区了。

**Comment by kejiacheng** [comment]
：)

**Comment by TheRenTOP** [comment]
这个js文件全部引入吗，还有有一个入口文件

**Comment by kejiacheng** [comment]
dist文件下kss.js

**Comment by TheRenTOP** [comment]
再问一个问题，截全屏是要用nw吗？怎么用的呢？

**Comment by kejiacheng** [comment]
对的，不然是没有办法的

**Comment by kejiacheng** [comment]
#6 用法在这条issues里讲过

**Comment by TheRenTOP** [comment]
这里的这个后端是指node.js，还是指公司项目的后端？

**Comment by kejiacheng** [comment]
后端语言
