### ISSUE TITLE
在一个很高可滚动的页面中startScreenShot()，只能截取页面最上面的一屏，但我当前在页面的底部

### ISSUE THREAD

**Issue by FridayDai** [kejiacheng/kscreenshot#20]
大神你好，在一个很高可滚动的页面中startScreenShot()，只能截取页面最上面的一屏，但我当前在页面的底部, 也就是说，截屏的时候他会跳转到页面的顶部？不能截取当前的屏幕位置吗？

**Comment by kejiacheng** [comment]
这个bug很早就发现了，我看没人提就一直没有解决了。我这两个礼拜抽个空看下吧。

**Comment by FridayDai** [comment]
> 这个bug很早就发现了，我看没人提就一直没有解决了。我这两个礼拜抽个空看下吧。

感谢，因为有需要用到您写的截图库，所以麻烦您帮忙修复一下

**Comment by kejiacheng** [comment]
嗯嗯 好的

**Comment by kejiacheng** [comment]
> > 这个bug很早就发现了，我看没人提就一直没有解决了。我这两个礼拜抽个空看下吧。
> 
> 感谢，因为有需要用到您写的截图库，所以麻烦您帮忙修复一下

这个问题修复了  更新下版本吧

**Comment by FridayDai** [comment]
> > > 这个bug很早就发现了，我看没人提就一直没有解决了。我这两个礼拜抽个空看下吧。
> > 
> > 
> > 感谢，因为有需要用到您写的截图库，所以麻烦您帮忙修复一下
> 
> 这个问题修复了 更新下版本吧

好的，十分感谢，我更新下试试
