### ISSUE TITLE
html2canvas 截图时css样式会有丢失，怎么办

### ISSUE THREAD

**Issue by FridayDai** [kejiacheng/kscreenshot#21]
kscreenshot 截图时css样式和页面上的不一样，导致有些想截图的内容截不对或者截不全，大神这个有什么好的解决方案吗

**Comment by kejiacheng** [comment]
这个我没有办法解决。

**Comment by kejiacheng** [comment]
或者你让后端给你一个整个页面的图片，然后覆盖在页面上

**Comment by FridayDai** [comment]
> html2canvas 截图时css样式会有丢失，怎么办



> 这个我没有办法解决。

我也尝试了一些办法，确实没有什么很好的办法

**Comment by FridayDai** [comment]
> 或者你让后端给你一个整个页面的图片，然后覆盖在页面上

**Comment by FridayDai** [comment]
> 或者你让后端给你一个整个页面的图片，然后覆盖在页面上

对了，昨天提的那个高度的issue，我今天试了，截图区域选完后还是高度不对呀

**Comment by kejiacheng** [comment]
是和以前一样  还是已经有区别了。

**Comment by FridayDai** [comment]
> 是和以前一样 还是已经有区别了。

有区别了，但是选中的区域会变，不是我框的那块图

**Comment by kejiacheng** [comment]
哦 我大致知道原因了，应该是分辨率的问题。

**Comment by FridayDai** [comment]
> > 是和以前一样 还是已经有区别了。
> 
> 有区别了，但是选中的区域会变，不是我框的那块图

> 哦 我大致知道原因了，应该是分辨率的问题。

我看你的高度是写死的，这个好解决吗？

**Comment by kejiacheng** [comment]
> > > 是和以前一样 还是已经有区别了。
> > 
> > 
> > 有区别了，但是选中的区域会变，不是我框的那块图
> 
> > 哦 我大致知道原因了，应该是分辨率的问题。
> 
> 我看你的高度是写死的，这个好解决吗？

好了  我改了重新发了

**Comment by FridayDai** [comment]
> > > > 是和以前一样 还是已经有区别了。
> > > 
> > > 
> > > 有区别了，但是选中的区域会变，不是我框的那块图
> > 
> > 
> > > 哦 我大致知道原因了，应该是分辨率的问题。
> > 
> > 
> > 我看你的高度是写死的，这个好解决吗？
> 
> 好了 我改了重新发了

卧槽，这么快

**Comment by kejiacheng** [comment]
> > > > > 是和以前一样 还是已经有区别了。
> > > > 
> > > > 
> > > > 有区别了，但是选中的区域会变，不是我框的那块图
> > > 
> > > 
> > > > 哦 我大致知道原因了，应该是分辨率的问题。
> > > 
> > > 
> > > 我看你的高度是写死的，这个好解决吗？
> > 
> > 
> > 好了 我改了重新发了
> 
> 卧槽，这么快

有一个地方疏忽了。你一下说，我差不多就明白了

**Comment by FridayDai** [comment]
> > > > > > 是和以前一样 还是已经有区别了。
> > > > > 
> > > > > 
> > > > > 有区别了，但是选中的区域会变，不是我框的那块图
> > > > 
> > > > 
> > > > > 哦 我大致知道原因了，应该是分辨率的问题。
> > > > 
> > > > 
> > > > 我看你的高度是写死的，这个好解决吗？
> > > 
> > > 
> > > 好了 我改了重新发了
> > 
> > 
> > 卧槽，这么快
> 
> 有一个地方疏忽了。你一下说，我差不多就明白了

我update了，试了一下OK，十分感谢

**Comment by kejiacheng** [comment]
嗯嗯，好的

**Comment by 02220** [comment]
想问一下我使用1.0.0版本导出的样式为什么没有边框呢
