### ISSUE TITLE
这个在普通的jquery项目中如何引用呢?其他的js文件现在都是cdn或者本地引入的这个怎么用呢？

### ISSUE THREAD

**Issue by XingGuan** [kejiacheng/kscreenshot#22]

**Comment by kejiacheng** [comment]
直接把dist/kss.js 文件复制一份到你本地吧

**Comment by XingGuan** [comment]
我已经这样试过但是使用的过程中碰到了问题，
new kscreenshot(
    {
        key: 65 
    }
)
这个无法使用，提示错误，另外我的页面中如果已经有一个canvas，再用这个截图，我原来的canvas内容消失，这个应该怎么改呢？
![image](https://user-images.githubusercontent.com/34224213/59650962-a59d3a00-91ba-11e9-8de2-fefe208835b7.png)

**Comment by kejiacheng** [comment]
kscreenshot 这个错误提示，应该是你引用的有问题。
你得保证在用kscreenshot的时候，已经引用了我的这个插件
