### ISSUE TITLE
可以写一个关闭按钮的回调嘛

### ISSUE THREAD

**Issue by pokface** [kejiacheng/kscreenshot#23]
完成之后后回调，toolbar关闭按钮后想把electron新开的页面通过回调close

**Comment by kejiacheng** [comment]
关闭按钮没有回调    但是有整个截图结束后的回调endCB，应该能满足你这个需求吧

**Comment by pokface** [comment]
有没有electron中使用的推荐方案，我目前的做法是新开一个窗口然后在这个窗口引入插件初始化，但是窗口出现了不能透明的问题只能拿到全屏幕截图传给窗口做背景然后截取，在截图完成后需要销毁这个窗口，endcb可以在完成后操作，但是没有关闭按钮的回调，关闭之后没法通知主进程销掉这个窗口。。。大佬求拯救，看了一圈的截图功能就你这个还蛮好用

**Comment by kejiacheng** [comment]
嗯嗯 了解了  我加一下

**Comment by pokface** [comment]
感谢大佬 膜拜

**Comment by kejiacheng** [comment]
写好了，你试试吧

**Comment by pokface** [comment]
好！ 感谢大佬 我试试
