### ISSUE TITLE
能直接进行上传不

### ISSUE THREAD

**Issue by kjtown** [kejiacheng/kscreenshot#25]
能不能直接写个接口，可以把截图进行上传，或与其它上传接口对接，这样就会比较方便，不要先保存，再操作去进行上传。能沟通一下不，QQ：349186394

**Comment by kejiacheng** [comment]
没怎么明白你的意思。

我这边只是一个前端插件，不会包括接口的，后续需要后端配合的东西，得你们自己完成的。

**Comment by kjtown** [comment]
嗯，是前端，接口上传肯定是另外接口去完成，但是我的意思是这个插件，能不能直接输出一个对象或流，能让接口直接去处理上传。这样对接就很顺畅了。

**Comment by kejiacheng** [comment]
endCB回调的第一个参数是你截图的base64，然后通过这base64应该能上传

**Comment by kjtown** [comment]
不好意思，忙着了，endCB要在页面中怎么调用才能获取到base64

**Comment by kejiacheng** [comment]
这个函数的第一个参数就是

**Comment by kjtown** [comment]
我没看明白回调函数要怎么传过去。

**Comment by kejiacheng** [comment]
这是插件初始化的时候，可以传endCB 然后endCb的第一个参数是base64

**Comment by kjtown** [comment]
new kscreenshot(
    {
        key: 65 ,
        endCB(){
                      回调函数代码
             }
    }
)
这样写就可以了是不

**Comment by kejiacheng** [comment]
额，邮件里居然没看到你的最后一句话。是的就是你这么写的

**Comment by kjtown** [comment]
//65指键盘中的A
new kscreenshot(
    {
        key: 65,
        endCB(){
            console.log("----------回调");
        }
    }
)
可是我截图完成，并没有打印这句回调语句。

**Comment by kejiacheng** [comment]
我自己测试了下没有问题的

**Comment by kejiacheng** [comment]
这个按钮是你点击完成后才会触发的

**Comment by kjtown** [comment]
我是点击完成后，没有触发这个函数

**Comment by kjtown** [comment]
方便加你QQ一下不，我的QQ：349186394

**Comment by kejiacheng** [comment]
好的

**Comment by kejiacheng** [comment]
我这边已经加你了

**Comment by kjtown** [comment]
没看到好友信息

**Comment by kejiacheng** [comment]
还没有吗？我的是375615453
