### ISSUE TITLE
我是将源码转换成ES5风格后，开始截图的时候会影响其他页面元素的显示

### ISSUE THREAD

**Issue by yanglin526000** [kejiacheng/kscreenshot#26]
求大神解答

**Comment by kejiacheng** [comment]
是截完图后导致其他页面样式变了；还是截图中的时候有问题，然后截完图后就正常了

**Comment by yanglin526000** [comment]
截图中不正常，截图后正常，不正常的高度我已经弄好了（去掉 scrollY: 200），但是截图中的不正常样式还是没能解决

**Comment by kejiacheng** [comment]
截图中的样式不一致这个目前没有特别好的解决方式。如果有条件的话，最好是让后端返回一个当前页面的截图，然后将这个截图覆盖到页面上，然后再这个截图上操作。最后截完图后再endCB里面将这个截图删了。

**Comment by yanglin526000** [comment]
![image](https://user-images.githubusercontent.com/41976072/62855134-fbf2a900-bd23-11e9-8473-434bcc05f332.png)
可以问问上面本来是正常的图标，为啥会变成下面的样式吗？代码大概是在哪个地方？
![image](https://user-images.githubusercontent.com/41976072/62855202-26dcfd00-bd24-11e9-8ec4-ed5493045cfb.png)

**Comment by kejiacheng** [comment]
应该是跨域的问题，你把这个字体弄到本地应该就没问题

**Comment by kejiacheng** [comment]
但是这不能根本解决跨域的问题

**Comment by yanglin526000** [comment]
好吧 谢谢你的细心解答 我再看看

**Comment by kejiacheng** [comment]
嗯嗯 好的
