### ISSUE TITLE
pdf截图  生成截图手势时很慢

### ISSUE THREAD

**Issue by wxy8855723** [kejiacheng/kscreenshot#29]
图片很快,生成pdf很慢和什么有关系,应该从哪里优化,
0ms html2canvas: html2canvas 1.0.0-alpha.11
kss.js:1 48889ms html2canvas (16db5981a10): Canvas renderer initialized (340x0 at 0,0) with scale 1
kss.js:1 48939ms html2canvas: Canvas renderer initialized (1920x979 at 0,0) with scale 1

**Comment by kejiacheng** [comment]
你说的生成pdf是什么意思，我这个插件没有这个功能吧

**Comment by wxy8855723** [comment]
> 你说的生成pdf是什么意思，我这个插件没有这个功能吧

就是我要实现在不同文件上截图,txt image pdf   前两个调用startScreenShot()方法生成截图手势很快,代表我可以截图了  pdf生成的非常慢

**Comment by kejiacheng** [comment]
这个速度受html2canvas的影响，应该是它在pdf转canvas时，解析的比较慢

**Comment by wxy8855723** [comment]
> 这个速度受html2canvas的影响，应该是它在pdf转canvas时，解析的比较慢

这个可以优化吗

**Comment by kejiacheng** [comment]
我这边是没法优化的。
