### ISSUE TITLE
当截图页面有ifame或者canvas的时候会有bug

### ISSUE THREAD

**Issue by qmhc** [kejiacheng/kscreenshot#3]
我尝试在一个使用了webGL和ifame的页面上截图，发现原来的GL的canvas会变黑，以及ifame会重叠

**Comment by qmhc** [comment]
可能是因为原页面上的canvas和ifame有异步js处理，在kss把当前页面复制到ifame的时候没有执行到那部分js，才导致了现在的问题

**Comment by kejiacheng** [comment]
我页面转成canvas使用的是html2canvas，应该是无法识别，这个问题暂时无法处理，不好意思

**Comment by betterRunner** [comment]
> https://github.com/niklasvh/html2canvas/issues/1461
这个应该是html2canvas的一个bug，读取iframe的资源的时候采用相对路径而不是绝对路径，我按照上面的解决方案改写了html2canvas可以正常对iframe截图

**Comment by langlanglanglanglang** [comment]
> > [niklasvh/html2canvas#1461](https://github.com/niklasvh/html2canvas/issues/1461)
> > 这个应该是html2canvas的一个bug，读取iframe的资源的时候采用相对路径而不是绝对路径，我按照上面的解决方案改写了html2canvas可以正常对iframe截图

您好，请问您有没有解决了这个BUG的编译版代码？如果有的话，可不可以发到我的邮箱（w1203315598@qq.com）？十分感谢！

**Comment by xxc12138** [comment]
> > > [niklasvh/html2canvas#1461](https://github.com/niklasvh/html2canvas/issues/1461)
> > > 这个应该是html2canvas的一个bug，读取iframe的资源的时候采用相对路径而不是绝对路径，我按照上面的解决方案改写了html2canvas可以正常对iframe截图
> 
> 您好，请问您有没有解决了这个BUG的编译版代码？如果有的话，可不可以发到我的邮箱（[w1203315598@qq.com](mailto:w1203315598@qq.com)）？十分感谢！

楼上的有发你吗，能否发我一份，谢谢（494202595@qq.com）
