### ISSUE TITLE
大佬，问下。怎么结合electron 实现 全屏截图？

### ISSUE THREAD

**Issue by storagess** [kejiacheng/kscreenshot#30]
大佬，问下。怎么结合electron 实现 全屏截图？

**Comment by kejiacheng** [comment]
https://github.com/kejiacheng/kscreenshot/issues/6#issuecomment-430064545 可以看这个issue，思路和nw类似

**Comment by storagess** [comment]
不会node  - -

**Comment by kejiacheng** [comment]
你可以让你们公司后端给你张全屏幕的截图就行

**Comment by storagess** [comment]
大佬，是什么意思？我调用接口获取一张全屏幕的图，然后怎么配合到你的这个插件？

**Comment by storagess** [comment]
@kejiacheng  大佬，没明白。那拿到图片怎么结合你的插件？

**Comment by kejiacheng** [comment]
额， 然后把这个图片放到这个透明无边框的窗口上，再直接调用我的插件就行了

**Comment by storagess** [comment]
@kejiacheng  不是很明白。。无边框窗口能附加图片吗。

**Comment by storagess** [comment]
@kejiacheng  大佬有空给个demo看看嘛

**Comment by kejiacheng** [comment]
可以加图片的，你自己先去了解下吧。

**Comment by storagess** [comment]
@kejiacheng  是不是弄一个透明的不显示的全屏窗口，然后里面载入一张图片就行了？

**Comment by kejiacheng** [comment]
嗯嗯 是的哦
