### ISSUE TITLE
截图完成

### ISSUE THREAD

**Issue by faimanlin** [kejiacheng/kscreenshot#32]
是否可以加一个截图完之后,直接enter,不用点击完成?

**Comment by kejiacheng** [comment]
这个目前不支持哦

**Comment by kejiacheng** [comment]
这个问题其实你可以自己hack，触发enter事件时js代码触发完成的click事件。

**Comment by faimanlin** [comment]
嗯嗯,谢谢.已经解决了.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"柯嘉诚"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 中午11:26
收件人:&nbsp;"kejiacheng/kscreenshot"<kscreenshot@noreply.github.com&gt;;
抄送:&nbsp;"."hui"<182235699@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kejiacheng/kscreenshot] 截图完成 (#32)




这个问题其实你可以自己hack，触发enter事件时js代码触发完成的click事件。

**Comment by kejiacheng** [comment]
嗯嗯 好的
