### ISSUE TITLE
在electron开发中在html2canvas这一步的时候，样式会乱掉

### ISSUE THREAD

**Issue by xiongtongzi** [kejiacheng/kscreenshot#35]
![image](https://user-images.githubusercontent.com/19956089/69593270-c1432100-1033-11ea-922b-676672dda9e4.png)
生成canvas这一步的时候样式没有引用到，你们开发的时候遇到了吗？
在正常的web页面则为正常，但是electron-build之后就会发生这种问题，初步判断是生成canvas的时候css样式路径不对

**Comment by kejiacheng** [comment]
这种情况我没有遇到过，不过html2canvas他是不会生成css的吧

**Comment by kejiacheng** [comment]
你这个在electron里面，截图前样式是正常的吗？

**Comment by xiongtongzi** [comment]
我把上层的canvas右移了，  前面的红框框是我原本的样式。  但是我看html2canvas是有复制css的操作，我继续研究一下吧

**Comment by kejiacheng** [comment]
嗯嗯，不过看你的描述，应该是和插件没有关系，你需要看一下为什么electron后样式引用不到了

**Comment by xiongtongzi** [comment]
![image](https://user-images.githubusercontent.com/19956089/69594735-3d3f6800-1038-11ea-985e-a7de17a3f22c.png)
嗯,页面样式是没问题的，我去看看html2canvas是怎么写的

**Comment by kejiacheng** [comment]
嗯嗯 好的
