### ISSUE TITLE
跨网页截图

### ISSUE THREAD

**Issue by liruijiang** [kejiacheng/kscreenshot#36]
可以截图另一个网页中的内容吗

**Comment by kejiacheng** [comment]
如果只是在网页中用截图，那肯定不行的。

**Comment by xiaoyantou** [comment]
大佬，我是用electron重新开一个透明的窗体。唤起截图时会自带一个白色的背景。导致全屏都是白色背景。截不到桌面上的图。请大佬说下思路。
