### ISSUE TITLE
整张截图布局错乱是什么情况

### ISSUE THREAD

**Issue by pangshaohua** [kejiacheng/kscreenshot#40]

**Comment by kejiacheng** [comment]
是图片跨域的问题吗

**Comment by rocky-191** [comment]
发现如果页面上有特殊的css样式，截图的时候生成canvas图片会不一致。比如某个地方有下面的css`.sys-title {
  font-family: "fzzzhonghjw", sans-serif;
  background-image: -webkit-linear-gradient(bottom, #8792a4, #ffffff);
  background-clip: text;
}`
字体类型是自己引入的字体。

**Comment by kejiacheng** [comment]
搜了一下，canvas是可以用引入的字体的。可能是html2canvas这个插件，没有做这种处理
