### ISSUE TITLE
截图input内的文字 显示靠下

### ISSUE THREAD

**Issue by blackNeting** [kejiacheng/kscreenshot#41]
正常情况下的input输入框有个margin-top 截图之后的样式里面也有margin-top　但是ｉｎｐｕｔ里面的文字确实显示的靠下了

**Comment by Aprodebug** [comment]
.kssBody #kss 原因是 这个下面有个postion:fixed

**Comment by blackNeting** [comment]
![image](https://user-images.githubusercontent.com/39954869/76293636-62f13400-62ec-11ea-9e2e-7ccaa38d7626.png)

**Comment by blackNeting** [comment]
@kejiacheng

**Comment by kejiacheng** [comment]
这个要改，只能在html2Canvas这个包下面改。要不你直接到这个包下面提个pr?

**Comment by kejiacheng** [comment]
因为我用的这个包，把页面转成Canvas的
