### ISSUE TITLE
关于IE适配的问题

### ISSUE THREAD

**Issue by xxc12138** [kejiacheng/kscreenshot#44]
大佬，关于IE环境使用的时候，会报错控制台输出“SCRIPT1006：缺少‘)’” 错误。我定位了一下问题点，感觉是这里不应该加引号的问题
![image](https://user-images.githubusercontent.com/37166156/79932020-094d5f00-847f-11ea-991a-04a71a7af505.png)![image](https://user-images.githubusercontent.com/37166156/79932039-15d1b780-847f-11ea-8754-24fbe5a81821.png)

**Comment by kejiacheng** [comment]
不好意思哈，这个插件没有考虑浏览器兼容性的
