### ISSUE TITLE
麻烦问一下，为什么在启用截屏的时候会改变我的页面文字大小

### ISSUE THREAD

**Issue by 286209330** [kejiacheng/kscreenshot#45]

**Comment by kejiacheng** [comment]
是页面上所有的文字都改变了大小吗。

**Comment by 286209330** [comment]
感谢回复，已经解决了，不能用html2cavans，我换了domtoimg，名字不太记得了，就是另一种方法，现在正常了，不过只能用静态文件了




在2020年04月29日 10:38，柯嘉诚 写道：

是页面上所有的文字都改变了大小吗。

**Comment by kejiacheng** [comment]
嗯嗯
