### ISSUE TITLE
保存截图报错，是什么原因？

### ISSUE THREAD

**Issue by lpcrystal** [kejiacheng/kscreenshot#5]
![image](https://user-images.githubusercontent.com/30790651/44561256-84c8ab80-a786-11e8-92f5-408c4a694464.png)

**Comment by kejiacheng** [comment]
能看一下  你传的参数吗

**Comment by lpcrystal** [comment]
不好意思，是我的问题，我没有传endCB参数。
另外请问：
触发截屏事件能不能用按钮控制，因为shift键与我的地图缩放有冲突

**Comment by kejiacheng** [comment]
endCB是可以不传的，但是如果穿了的话，必须是function

可以用按钮控制的,将key设置为null ,然后用startScreenShot方法
