### ISSUE TITLE
大神，您好！您的截图插件很棒啊，特别是你最后的demo。

### ISSUE THREAD

**Issue by coxieIns** [kejiacheng/kscreenshot#6]
我再使用中发现只能截本窗体的图，不知道你最后的demo是如何实现的，能分享一下吗？谢谢了！

**Comment by kejiacheng** [comment]
思路是用nw打开一个透明无边框全屏的新窗口，然后通过后端（我是通过node）返回显示屏的截图，接下来直接调用我的这个插件就行了

**Comment by coxieIns** [comment]
明白了，谢谢您。


| |
陈明
邮箱：coxie@126.com
|

签名由 网易邮箱大师 定制

在2018年10月16日 09:00，柯嘉诚 写道：

思路是用nw打开一个透明无边框全屏的新窗口，然后通过后端（我是通过node）返回显示屏的截图，接下来直接调用我的这个插件就行了
