### ISSUE TITLE
如果不用nodejs 该怎么实现功能呢

### ISSUE THREAD

**Issue by huihaiwang** [kejiacheng/kscreenshot#7]
现在的项目没用nodejs要实现微信截图类似功能 看半天感觉项目主的这个项目较为理想,就是单纯js怎么实现呢

**Comment by kejiacheng** [comment]
如果知识浏览器端的截图，我这是单纯用js实现的。不过如果是客户端的话，我这个项目也是要依赖后端的，因为前端无法获取整个屏幕的视窗，需要依赖后端给我一个整个屏幕的截图
