### ISSUE TITLE
请求项目主出个demo 

### ISSUE THREAD

**Issue by huihaiwang** [kejiacheng/kscreenshot#8]
我是学习后端的 前端的看不太懂,请求项目主出个demo 能直接使用

**Comment by kejiacheng** [comment]
纯前端的项目demo已经有了，客户端的demo代码我这之前换了台电脑后丢了。我周末看下时间写下

**Comment by kejiacheng** [comment]
https://github.com/kejiacheng/kscreenshot/issues/6#issuecomment-430064545 具体的思路是这样的

**Comment by kjtown** [comment]
帅哥，能给前端使用的DEMO出来看一下不。
